Repository anakmagang/anakmagang, pull requests merged in 2022-10, with the labels that each got.

#16 docs : programmer diluar nalar coy
  bio
Labels: hacktoberfest-accepted

#17 Keinjek #ehh
  bio
Labels: hacktoberfest-accepted

#11 Joke bpk bpk FE
  bio
Labels: hacktoberfest-accepted

#20 mana sy tw
  bio
Labels: automerge, kodiak: merge.method = 'rebase'

#9 anakMagangTersakiti
  bio
Labels: automerge, kodiak: merge.method = 'squash'

#13 bersinar terang seperti surya walaupun gelap
  bio
Labels: automerge, kodiak: merge.method = 'squash'

#21 Update bio
  bio
Labels: automerge, kodiak: merge.method = 'squash'

#23 commit hahay
  bio
Labels: automerge, kodiak: merge.method = 'squash'

#22 Update bio
  bio
Labels: automerge, kodiak: merge.method = 'squash'

#24 kapan gajian ?:(
  bio
Labels: automerge, kodiak: merge.method = 'rebase'

#25 naik naik
  bio
Labels: automerge, kodiak: merge.method = 'rebase'

#26 Update
  bio
Labels: automerge, kodiak: merge.method = 'rebase'

#28 Update bio
  bio
Labels: automerge, kodiak: merge.method = 'rebase'
